import { Home, Car, Baby, Dog, Cat, Rat } from 'lucide-vue-next';

export const STEPS = ['Infos générales', 'Médias', 'Affinités', 'Détails', 'Résumé'];

export const SPECIES_OPTIONS = [
    { value: 'chat', label: 'Chat' },
    { value: 'chien', label: 'Chien' },
    { value: 'lapin', label: 'Lapin' },
    { value: 'oiseau', label: 'Oiseau' },
    { value: 'rongeur', label: 'Rongeur' },
    { value: 'autre', label: 'Autre' }
];

export const AGE_OPTIONS = [
    { value: '0-1', label: '0-1 an' },
    { value: '1-3', label: '1-3 ans' },
    { value: '3-7', label: '3-7 ans' },
    { value: '7+', label: '7+ ans' }
];

export const SEX_OPTIONS = [
    { value: 'male', label: 'Mâle' },
    { value: 'female', label: 'Femelle' }
];

export const SIZE_OPTIONS = [
    { value: 'petit', label: 'Petit' },
    { value: 'moyen', label: 'Moyen' },
    { value: 'grand', label: 'Grand' }
];

export const WEIGHT_OPTIONS = [
    { value: '0-5', label: '0-5 kg' },
    { value: '5-10', label: '5-10 kg' },
    { value: '10-20', label: '10-20 kg' },
    { value: '20-30', label: '20-30 kg' },
    { value: '30+', label: '30+ kg' }
];

export const TRAINING_OPTIONS = [
    { value: 'éduqué', label: 'éduqué' },
    { value: 'facile à dresser', label: 'facile à dresser' },
    { value: 'habitué à la laisse', label: 'habitué à la laisse' },
    { value: 'têtu', label: 'têtu' }
];

export const PERSONALITY_OPTIONS = [
    { value: 'calme', label: 'calme' },
    { value: 'énergique', label: 'énergique' },
    { value: 'indépendant', label: 'indépendant' },
    { value: 'affectueux', label: 'affectueux' },
    { value: 'curieux', label: 'curieux' },
    { value: 'joueur', label: 'joueur' },
    { value: 'bavard', label: 'bavard' },
    { value: 'câlin', label: 'câlin' },
    { value: 'sociable', label: 'sociable' },
    { value: 'timide', label: 'timide' }
];

export const ENV_OPTIONS = [
    { value: 'appartement', label: 'appartement', icon: Home },
    { value: 'voiture', label: 'voiture', icon: Car },
    { value: 'enfant', label: 'enfant', icon: Baby },
    { value: 'chien', label: 'chien', icon: Dog },
    { value: 'chat', label: 'chat', icon: Cat },
    { value: 'autre animaux', label: 'autre animaux', icon: Rat }
];


export const DOG_BREEDS = [
    "Affenpinscher",
    "Lévrier afghan",
    "Chien de l'Atlas (Aïdi)",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Alano espagnol",
    "Klee Kai d'Alaska",
    "Malamute de l'Alaska",
    "Basset des Alpes",
    "Épagneul des Alpes",
    "Bouledogue américain",
    "Cocker américain",
    "Esquimau américain",
    "Foxhound américain",
    "Terrier américain sans poil",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "Épagneul d'eau américain",
    "Anglo-Français de Petite Vénerie",
    "Bouvier de l'Appenzell",
    "Braque de l'Ariège",
    "Ariégeois",
    "Berger égyptien (Armant)",
    "Gampr arménien",
    "Chien d'Artois",
    "Bouvier australien",
    "Kelpie australien",
    "Berger australien",
    "Terrier soyeux australien",
    "Bouvier australien courte queue",
    "Terrier australien",
    "Azawakh",
    "Berger de Bakharwal",
    "Barbet",
    "Basenji",
    "Berger basque",
    "Basset artésien normand",
    "Basset bleu de Gascogne",
    "Basset fauve de Bretagne",
    "Basset Hound",
    "Chien de rouge de Bavière",
    "Beagle",
    "Beagle-Harrier",
    "Colley barbu (Bearded Collie)",
    "Beauceron",
    "Bedlington Terrier",
    "Berger belge (Groenendael)",
    "Berger belge (Laekenois)",
    "Berger belge (Malinois)",
    "Berger de Bergame",
    "Berger blanc suisse",
    "Berger picard",
    "Chien courant bernois",
    "Bouvier bernois",
    "Billy",
    "Coonhound noir et feu",
    "Foxhound noir et feu de Virginie",
    "Chien d'élan norvégien noir",
    "Terrier noir russe",
    "Chien de Saint-Hubert (Bloodhound)",
    "Blue Lacy",
    "Blue Paul Terrier",
    "Boerboel",
    "Berger de Bohême",
    "Bolognais",
    "Border Collie",
    "Border Terrier",
    "Barzoï",
    "Boston Terrier",
    "Bouvier des Ardennes",
    "Bouvier des Flandres",
    "Boxer",
    "Épagneul Boykin",
    "Braque italien",
    "Braque d'Auvergne",
    "Braque du Bourbonnais",
    "Braque du Puy",
    "Braque français",
    "Braque Saint-Germain",
    "Terrier brésilien",
    "Briard",
    "Briquet griffon vendéen",
    "Épagneul breton",
    "Broholmer",
    "Chien courant du Jura (Bruno)",
    "Berger de Bucovine",
    "Bull and Terrier",
    "Bull Terrier (Miniature)",
    "Bull Terrier",
    "Bulldog (Bouledogue anglais)",
    "Bullenbeisser",
    "Bullmastiff",
    "Bully Kutta",
    "Perdiguero de Burgos",
    "Cairn Terrier",
    "Chien de Canaan",
    "Chien inuit canadien",
    "Cane Corso",
    "Welsh Corgi Cardigan",
    "Chien de Caroline",
    "Chien de berger des Carpates",
    "Chien léopard catahoula",
    "Berger catalan",
    "Berger du Caucase",
    "Cavalier King Charles",
    "Berger d'Asie centrale",
    "Barbu tchèque",
    "Terrier tchèque",
    "Retriever de la baie de Chesapeake",
    "Chien français blanc et noir",
    "Chien français blanc et orange",
    "Chien français tricolore",
    "Chien-gris",
    "Chihuahua",
    "Fox-terrier chilien",
    "Chien de Chongqing",
    "Chien chinois à crête",
    "Chien impérial chinois",
    "Chinook",
    "Chippiparai",
    "Chow-chow",
    "Cierny Sery",
    "Cimarron uruguayen",
    "Cirneco de l'Etna",
    "Clumber Spaniel",
    "Combai",
    "Chien de combat de Cordoba",
    "Coton de Tuléar",
    "Chien courant crétois",
    "Berger croate",
    "Berger de Cumberland",
    "Retriever à poil bouclé",
    "Cursinu",
    "Berger de la Serra de Aires",
    "Chien de Castro Laboreiro",
    "Fila de Saint Miguel",
    "Teckel",
    "Dalmatien",
    "Dandie Dinmont Terrier",
    "Chien de ferme dano-suédois",
    "Brachet allemand",
    "Dobermann",
    "Dogue argentin",
    "Dogue cubain",
    "Dogue de Bordeaux",
    "Chien de perdrix de Drente",
    "Basset suédois (Drever)",
    "Chien courant norvégien (Dunker)",
    "Berger hollandais",
    "Smous des Pays-Bas",
    "Laika de Sibérie orientale",
    "Berger d'Europe de l'Est",
    "Elo",
    "Cocker Spaniel anglais",
    "Foxhound anglais",
    "Mastiff (Dogue anglais)",
    "Setter anglais",
    "Berger anglais",
    "Springer anglais",
    "Toy Terrier anglais (Noir et Feu)",
    "Épagneul d'eau anglais",
    "Terrier blanc anglais",
    "Bouvier de l'Entlebuch",
    "Chien courant d'Estonie",
    "Chien de la Serra da Estrela",
    "Eurasier",
    "Field Spaniel",
    "Fila Brasileiro",
    "Chien courant finnois",
    "Chien finnois de Laponie",
    "Spitz finlandais",
    "Retriever à poil plat",
    "Chien de montagne de Formose",
    "Fox-terrier (à poil lisse)",
    "Bouledogue français",
    "Épagneul français",
    "Galgo espagnol",
    "Gascon saintongeois",
    "Chien d'arrêt allemand à poil long",
    "Pinscher allemand",
    "Berger allemand",
    "Braque allemand à poil court",
    "Oysel allemand",
    "Spitz allemand",
    "Braque allemand à poil dur",
    "Schnauzer géant",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Setter Gordon",
    "Dogue de Porto Rico (Gran Mastín de Borínquen)",
    "Grand anglo-français blanc et noir",
    "Grand anglo-français blanc et orange",
    "Grand anglo-français tricolore",
    "Grand basset griffon vendéen",
    "Grand bleu de Gascogne",
    "Grand griffon vendéen",
    "Dogue allemand (Grand Danois)",
    "Chien de montagne des Pyrénées (Patou)",
    "Grand bouvier suisse",
    "Chien courant grec",
    "Chien du Groenland",
    "Lévrier (Greyhound)",
    "Griffon bleu de Gascogne",
    "Griffon bruxellois",
    "Griffon fauve de Bretagne",
    "Griffon nivernais",
    "Chien courant de Hamilton",
    "Chien de rouge du Hanovre",
    "Chien des Indiens Hare",
    "Harrier",
    "Bichon havanais",
    "Poi hawaïen",
    "Berger de l'Himalaya",
    "Hokkaido",
    "Hovawart",
    "Huntaway",
    "Chien courant de Hygen",
    "Podenco d'Ibiza",
    "Berger islandais",
    "Chien paria indien",
    "Spitz indien",
    "Setter irlandais rouge et blanc",
    "Setter irlandais",
    "Terrier irlandais",
    "Épagneul d'eau irlandais",
    "Lévrier irlandais (Wolfhound)",
    "Chien courant d'Istrie à poil dur",
    "Chien courant d'Istrie à poil ras",
    "Petit lévrier italien",
    "Jack Russell Terrier",
    "Jagdterrier",
    "Chien d'élan suédois (Jämthund)",
    "Kai Toraken",
    "Kaikadi",
    "Kanni",
    "Chien d'ours de Carélie",
    "Berger du Karst",
    "Spitz-Loup (Keeshond)",
    "Kerry Beagle",
    "Kerry Blue Terrier",
    "Épagneul King Charles",
    "Berger royal (King Shepherd)",
    "Kintamani",
    "Kishu",
    "Komondor",
    "Kooikerhondje",
    "Koolie",
    "Jindo coréen",
    "Kromfohrländer",
    "Mastiff de Kumaon",
    "Kurī",
    "Kuvasz",
    "Kyi-Leo",
    "Husky du Labrador",
    "Labrador Retriever",
    "Chien d'eau romagnol (Lagotto Romagnolo)",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Berger finnois de Laponie",
    "Grand épagneul de Münster",
    "Léonberg",
    "Lhassa Apso",
    "Chien courant lituanien",
    "Whippet à poil long",
    "Petit chien lion (Löwchen)",
    "Lévrier Mahratta",
    "Bichon maltais",
    "Terrier de Manchester",
    "Berger de Maremme et Abruzzes",
    "Berger McNab",
    "Chien nu du Mexique",
    "Berger américain miniature",
    "Berger australien miniature",
    "Fox-terrier miniature",
    "Pinscher nain",
    "Schnauzer nain",
    "Shar Pei miniature",
    "Molosse",
    "Chien courant de montagne du Monténégro",
    "Chien de garde de Moscou",
    "Chien d'eau de Moscou",
    "Mountain Cur",
    "Mucuchies",
    "Lévrier Mudhol",
    "Mudi",
    "Mâtin napolitain",
    "Chien de berger de Nouvelle-Zélande",
    "Terre-Neuve",
    "Épagneul de Norfolk",
    "Norfolk Terrier",
    "Spitz de Norrbotten",
    "Beagle du Nord",
    "Chien inuit du Nord",
    "Buhund norvégien",
    "Chien d'élan norvégien",
    "Chien norvégien de macareux (Lundehund)",
    "Norwich Terrier",
    "Lévrier croate",
    "Braque danois (Ancien)",
    "Bobtail (Ancien chien de berger anglais)",
    "Ancien Terrier anglais",
    "Ancien chien de berger allemand",
    "Bouledogue anglais (Olde English Bulldogge)",
    "Chien de loutre (Otterhound)",
    "Braque de Navarre",
    "Terrier de Paisley",
    "Pandikona",
    "Épagneul nain continental (Papillon)",
    "Parson Russell Terrier",
    "Patterdale Terrier",
    "Pékinois",
    "Welsh Corgi Pembroke",
    "Dogue des Canaries",
    "Dogue de Majorque",
    "Chien nu du Pérou",
    "Petit basset griffon vendéen",
    "Petit bleu de Gascogne",
    "Épagneul nain continental (Phalène)",
    "Chien du pharaon",
    "Chien de Phu Quoc",
    "Épagneul picard",
    "Plott Hound",
    "Podenco canario",
    "Pointer anglais",
    "Lévrier polonais",
    "Brachet polonais",
    "Chien de chasse polonais",
    "Berger polonais de plaine",
    "Berger des Tatras",
    "Spitz nain (Loulou de Poméranie)",
    "Épagneul de Pont-Audemer",
    "Caniche",
    "Porcelaine",
    "Podengo portugais",
    "Braque portugais",
    "Chien d'eau portugais",
    "Chien courant de la vallée de la Save",
    "Ratier de Prague",
    "Pudelpointer",
    "Carlin",
    "Puli",
    "Pumi",
    "Pungsan",
    "Matin des Pyrénées",
    "Berger des Pyrénées",
    "Rafeiro de l'Alentejo",
    "Rajapalayam",
    "Lévrier Rampur",
    "Rastreador Brasileiro",
    "Rat Terrier",
    "Ratier bodeguero andalou",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Colley à poil long",
    "Russell Terrier",
    "Épagneul russe",
    "Tracker russe",
    "Laika russo-européen",
    "Sabueso espagnol",
    "Épagneul de Saint-Usuge",
    "Husky de Sakhaline",
    "Saluki",
    "Samoyède",
    "Sapsali",
    "Schapendoes",
    "Chien courant de Schiller",
    "Schipperke",
    "Chien courant suisse",
    "Petit chien courant suisse",
    "Colley d'Écosse",
    "Lévrier écossais (Deerhound)",
    "Terrier écossais",
    "Sealyham Terrier",
    "Chien courant italien",
    "Chien de traîneau de Seppala",
    "Chien courant serbe",
    "Chien courant tricolore serbe",
    "Shar Pei",
    "Berger des Shetland",
    "Shiba Inu",
    "Shih Tzu",
    "Shikoku",
    "Berger de Shiloh",
    "Husky sibérien",
    "Silken Windhound",
    "Lévrier srilankais",
    "Skye Terrier",
    "Sloughi",
    "Tchouvatch slovaque",
    "Braque slovaque à poil dur",
    "Petit chien domestique grec",
    "Petit épagneul de Münster",
    "Colley à poil court",
    "Berger de Russie méridionale",
    "Southern Hound",
    "Mâtin espagnol",
    "Chien d'eau espagnol",
    "Spinone",
    "Sporting Lucas Terrier",
    "Saint-bernard",
    "Chien d'eau de Saint-Jean",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Schnauzer moyen",
    "Stephens Cur",
    "Chien courant de Styrie à poil dur",
    "Sussex Spaniel",
    "Chien suédois de Laponie",
    "Vallhund suédois (Spitz des Wisigoths)",
    "Chien d'ours de Tahltan",
    "Lévrier Taïgan",
    "Talbot",
    "Chien Tamaskan",
    "Teddy Roosevelt Terrier",
    "Telomian",
    "Tenterfield Terrier",
    "Bangkaew de Thaïlande",
    "Chien thaïlandais à crête dorsale",
    "Dogue du Tibet",
    "Épagneul tibétain",
    "Terrier tibétain",
    "Tornjak",
    "Tosa",
    "Toy Bulldog",
    "Toy Fox Terrier",
    "Toy Manchester Terrier",
    "Toy Trawler Spaniel",
    "Chien courant de Transylvanie",
    "Treeing Cur",
    "Treeing Walker Coonhound",
    "Trigg Hound",
    "Tweed Water Spaniel",
    "Chien courant tyrolien",
    "Vizsla (Braque hongrois)",
    "Volpino Italiano",
    "Braque de Weimar",
    "Chien de berger gallois",
    "Springer gallois",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Laika de Sibérie occidentale",
    "Basset de Westphalie",
    "Wetterhoun",
    "Whippet",
    "Berger blanc",
    "Fox-terrier à poil dur",
    "Korthals",
    "Braque hongrois à poil dur",
    "Yorkshire Terrier",
    "Chien de berger yougoslave (Charplanina)",
    "Autre / Croisé"
];

export const CAT_BREEDS = [
    'Abyssin',
    'American Bobtail',
    'American Curl',
    'American Shorthair',
    'American Wirehair',
    'Angora Turc',
    'Balinais',
    'Bengal',
    'Bleu Russe',
    'Bobtail Japonais',
    'Bombay',
    'British Longhair',
    'British Shorthair',
    'Burmese',
    'Burmilla',
    'Chartreux',
    'Chausie',
    'Cornish Rex',
    'Cymric',
    'Devon Rex',
    'Donskoy',
    'Européen (Gouttière)',
    'Exotic Shorthair',
    'German Rex',
    'Havana Brown',
    'Highland Fold',
    'Himalayen',
    'Javanais',
    'Korat',
    'Kurilian Bobtail',
    'LaPerm',
    'Maine Coon',
    'Manx',
    'Mau Égyptien',
    'Munchkin',
    'Nebelung',
    'Norvégien',
    'Ocicat',
    'Oriental',
    'Persan',
    'Peterbald',
    'Pixie-bob',
    'Ragamuffin',
    'Ragdoll',
    'Sacré de Birmanie',
    'Savannah',
    'Scottish Fold',
    'Scottish Straight',
    'Selkirk Rex',
    'Siamois',
    'Sibérien',
    'Singapura',
    'Snowshoe',
    'Sokoke',
    'Somali',
    'Sphynx',
    'Thaï',
    'Tonkinois',
    'Toyger',
    'Turc de Van',
    'York Chocolat',
    'Autre / Croisé'
];

export const RABBIT_BREEDS = [
    'Lapin Angora',
    'Lapin Bélier',
    'Lapin de Garenne',
    'Lapin Géant des Flandres',
    'Lapin Nain',
    'Lapin Papillon',
    'Lapin Polonais',
    'Lapin Rex',
    'Lapin Tête de Lion',
    'Autre / Croisé'
];

export const RODENT_BREEDS = [
    'Chinchilla',
    'Cochon d\'Inde (Cobaye)',
    'Dègue du Chili (Octodon)',
    'Écureuil de Corée',
    'Gerbille',
    'Hamster Chinois',
    'Hamster de Campbell',
    'Hamster Doré (Syrien)',
    'Hamster Roborovski',
    'Hamster Russe',
    'Rat Domestique',
    'Souris Domestique',
    'Autre Rongeur'
];

export const BIRD_BREEDS = [
    'Ara',
    'Cacatoès',
    'Canari',
    'Colombe / Tourterelle',
    'Conure',
    'Diamant (Gould, Mandarin...)',
    'Gris du Gabon',
    'Inséparable',
    'Mainate',
    'Perroquet Amazone',
    'Perruche à Collier',
    'Perruche Calopsitte',
    'Perruche Ondulée',
    'Pigeon',
    'Poule / Coq',
    'Autre Oiseau'
];

export const OTHER_NAC_BREEDS = [
    'Agame Barbu (Pogona)',
    'Axolotl',
    'Boa Constrictor',
    'Caméléon',
    'Furet',
    'Gecko à Crête',
    'Gecko Léopard',
    'Grenouille / Crapaud',
    'Iguane',
    'Pétaure (Sugar Glider)',
    'Python Royal',
    'Serpent des Blés',
    'Tortue d\'Eau',
    'Tortue de Terre',
    'Autre'
];


export const getBreedsForSpecies = (species) => {
    const normalizedSpecies = species ? species.toLowerCase() : '';

    switch (normalizedSpecies) {
        case 'chien': 
            return DOG_BREEDS;
        case 'chat': 
            return CAT_BREEDS;
        case 'lapin': 
            return RABBIT_BREEDS;
        case 'rongeur': 
            return RODENT_BREEDS;
        case 'oiseau': 
            return BIRD_BREEDS;
        case 'autre': 
            return OTHER_NAC_BREEDS;
        default: 
            return [];
    }
};